#!/bin/env bash

projroot=$1
std=c++17
include="$projroot/src/lib"
db=sqlite

odb \
    -d "$db" \
    --std "$std" \
    -I "$include" \
    --generate-query \
    --generate-schema \
    --hxx-suffix .h \
    --ixx-suffix .i \
    --cxx-suffix .cpp \
    -o "$projroot/src/lib/data" \
    "$projroot/src/lib/data/new.h"
